import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/contexts/AuthProvider";
import { UserProvider } from "@/contexts/UserContext";
import AuthGuard from "@/contexts/AuthGuard";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// Client-only theme sync component
function ThemeScript() {
	if (typeof window !== 'undefined') {
		const theme = window.localStorage.getItem('theme') || 'light';
		if (theme === 'dark') {
			document.documentElement.classList.add('dark');
		} else {
			document.documentElement.classList.remove('dark');
		}
	}
	return null;
}
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{/* Client-only theme sync */}
				<ThemeScript />
				<AuthProvider>
					<UserProvider>
						<AuthGuard>
							{children}
						</AuthGuard>
					</UserProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
