// Static campaign data for all types
export const campaigns = [
  {
    id: '1',
    customerId: 'customer1',
    service: 'Paid Social',
    media: 'META',
    campaignFormat: 'Video',
    countryCode: 'DK',
    startDate: '2025-12-01',
    endDate: '2026-01-01',
    campaignName: 'Winter Sale META',
    messageBrief: 'Promote winter sale on META',
    b2bOrB2c: 'B2C',
    budget: 5000,
    landingpage: 'https://example.com/winter',
    materialFromCustomer: 'Logo, product images',
    readyForApproval: false,
    status: 'Pending',
    commentToCustomer: '',
    createdAt: '2025-11-20',
    parentCampaignId: null,
    campaignType: 'Conversion',
    campaignDimensions: '1920x1080',
    campaignVariation: 'A',
    campaignTextToCreative: 'Winter is here! Save now.',
    campaignTextToCreativeTranslation: 'Vinteren er her! Spar nu.'
  },
  {
    id: '2',
    customerId: 'customer1',
    service: 'Paid Search',
    media: 'Google',
    campaignFormat: 'Search Ad',
    countryCode: 'DK',
    startDate: '2025-12-10',
    endDate: '2026-01-10',
    campaignName: 'New Year PPC',
    messageBrief: 'Drive traffic for New Year',
    b2bOrB2c: 'B2B',
    budget: 3000,
    landingpage: 'https://example.com/newyear',
    materialFromCustomer: 'Ad copy',
    readyForApproval: true,
    status: 'Approved',
    commentToCustomer: 'Ready to launch',
    createdAt: '2025-12-01',
    parentCampaignId: null,
    campaignType: 'Always On',
    campaignDimensions: '728x90',
    campaignVariation: 'B',
    campaignTextToCreative: 'Start your year with us.',
    campaignTextToCreativeTranslation: 'Start dit år med os.'
  },
  {
    id: '3',
    customerId: 'customer1',
    service: 'Email Marketing',
    media: 'Email',
    campaignFormat: 'Newsletter',
    countryCode: 'SE',
    startDate: '2025-12-15',
    endDate: '2026-01-15',
    campaignName: 'Holiday Newsletter',
    messageBrief: 'Seasonal offers for subscribers',
    b2bOrB2c: 'B2C',
    budget: 1000,
    landingpage: 'https://example.com/holiday',
    materialFromCustomer: 'Subscriber list',
    readyForApproval: false,
    status: 'Pending Customer Approval',
    commentToCustomer: 'Please review content',
    createdAt: '2025-12-05',
    parentCampaignId: null,
    campaignType: 'Conversion',
    campaignDimensions: '600x800',
    campaignVariation: 'A',
    campaignTextToCreative: 'Exclusive holiday deals!',
    campaignTextToCreativeTranslation: 'Exklusiva erbjudanden till jul!'
  },
  {
    id: '4',
    customerId: 'customer1',
    service: 'SEO',
    media: 'Website',
    campaignFormat: 'Landingpage',
    countryCode: 'NO',
    startDate: '2025-12-20',
    endDate: '2026-02-01',
    campaignName: 'SEO Landingpage',
    messageBrief: 'Optimize for winter keywords',
    b2bOrB2c: 'B2B',
    budget: 2000,
    landingpage: 'https://example.com/seo',
    materialFromCustomer: 'Keyword list',
    readyForApproval: true,
    status: 'Live',
    commentToCustomer: '',
    createdAt: '2025-12-10',
    parentCampaignId: null,
    campaignType: 'Always On',
    campaignDimensions: 'Full width',
    campaignVariation: 'C',
    campaignTextToCreative: 'Rank higher this winter.',
    campaignTextToCreativeTranslation: 'Rangér høyere denne vinteren.'
  }
];
